// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Connection: typeof import('./src/components/Connection.vue')['default']
    Decoder: typeof import('./src/components/Decoder.vue')['default']
    Demuxer: typeof import('./src/components/Demuxer.vue')['default']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    Renderer: typeof import('./src/components/Renderer.vue')['default']
  }
}
